name: hiepnx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.0
  path_provider: ^1.6.5
  shared_preferences: ^0.5.3+4
  flutter_svg: ^0.17.3+1
  easy_localization: ^2.3.2
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.3.1
  carousel_slider: ^2.2.1
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/data.db
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
